export const metadata = {
  title: 'Entrega 4',
  description: 'Generated by 1TDSPV RM551987',
}

export default function CalcaLayout({ children }) {
  return (
    <div>
      <h1>Minha Calças</h1>
      {children}

    </div>
    
  )
}