import './globals.css'
import { Inter } from 'next/font/google'
import Cabecalho from './componentes/cabecalho/cabecalho'
import Rodape from './componentes/rodape/rodape'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Entrega 4',
  description: 'Generated by create rm98525',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Cabecalho/>
        
        {children}
        <Rodape/>
        </body>
    </html>
  )
}
